# Generated by Django 2.0 on 2019-04-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_type',
        ),
    ]
