# Generated by Django 2.1.5 on 2019-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190225_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtest',
            name='type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
