# Generated by Django 2.1.5 on 2019-02-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190226_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='evaluationtest',
            new_name='Evaluationtest',
        ),
    ]
