# Generated by Django 2.1.5 on 2019-02-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190226_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Evaluationtest',
            new_name='evaluationtest',
        ),
    ]
