# Generated by Django 2.0.7 on 2019-03-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190226_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationtest',
            name='url',
            field=models.SlugField(default=0, help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationtest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='Category'),
        ),
    ]
